kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.11-alpine
    environment:
      GO111MODULE: "on"
    commands:
      - apk update && apk add make git
      - make test
      - make build
    when:
      event: [push,tag]

  - name: publish-dev
    image: plugins/docker
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    settings:
      repo: justinbarrick/backup-controller
      tags:
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    when:
      event: push

  - name: publish
    image: plugins/docker
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    settings:
      repo: justinbarrick/backup-controller
      tags:
        - ${DRONE_TAG}
        - latest
    when:
      event: tag

  - name: github_release
    image: plugins/github-release
    environment:
      github_token:
        from_secret: github_token
    settings:
      files:
        - backup-controller
      checksum:
        - sha256
    when:
      event: tag

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_url
      channel:
        from_secret: slack_channel
      username: Drone CI
      icon_url: https://i.imgur.com/B7Tk2Xf.png
      template: >
        {{#success build.status}}
          Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} succeeded!
        {{else}}
          Build <{{build.link}}|#{{build.number}}> for <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.commit}}|{{repo.name}}#{{build.branch}}> by {{build.author}} failed.
        {{/success}}
    when:
      status: [success, failure]
      event: [push,tag]

  - name: slack2
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_url
      channel:
        from_secret: slack_channel
      username: Fluxcloud Release Bot
      icon_url: https://i.imgur.com/B7Tk2Xf.png
      template: >
        Released ${DRONE_TAG} to <https://github.com/{{repo.owner}}/{{repo.name}}/releases/tag/${DRONE_TAG}|Github>.
  
        Pushed <https://hub.docker.com/r/{{repo.owner}}/{{repo.name}}|{{repo.owner}}/{{repo.name}}:${DRONE_TAG}> to Dockerhub.
    when:
      event: tag
